/**
 * Foundational System Error Codes
 * Common framework-independent error identifiers for validation, auth, and infrastructure.
 * Domain-specific error codes must be added in their respective domain phases.
 */

export const ErrorCodes = {
  // Common / Infrastructure
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Rate Limiting & Network
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',

  // LOGIC-008 Phase 10 — Domain Exception Taxonomy (6 Families)
  // 1. Transaction & Interaction Exceptions
  TRANSACTION_CANCELLED: 'TRANSACTION_CANCELLED',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
  TRANSACTION_TIMED_OUT: 'TRANSACTION_TIMED_OUT',
  TRANSACTION_ABANDONED: 'TRANSACTION_ABANDONED',

  // 2. Fulfillment & Delivery Exceptions
  DELIVERY_CUSTOMER_UNREACHABLE: 'DELIVERY_CUSTOMER_UNREACHABLE',
  PARTIAL_FULFILLMENT: 'PARTIAL_FULFILLMENT',
  ITEM_UNAVAILABLE_SUBSTITUTION: 'ITEM_UNAVAILABLE_SUBSTITUTION',
  SERVICE_EXECUTION_FAILED: 'SERVICE_EXECUTION_FAILED',

  // 3. Financial & Payment Exceptions
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_DISPUTED: 'REFUND_DISPUTED',
  EXTERNAL_FINANCIAL_TRANSACTION_FAILED: 'EXTERNAL_FINANCIAL_TRANSACTION_FAILED',

  // 4. Geographic & Coverage Exceptions
  GEOGRAPHIC_MISMATCH: 'GEOGRAPHIC_MISMATCH',
  PLACE_CLOSED_OR_RELOCATED: 'PLACE_CLOSED_OR_RELOCATED',

  // 5. Entity & Operational Status Exceptions
  PROVIDER_INACTIVE_OR_WITHDRAWN: 'PROVIDER_INACTIVE_OR_WITHDRAWN',
  BUSINESS_CLOSED: 'BUSINESS_CLOSED',

  // 6. Trust, Data & Moderation Exceptions
  DISPUTED_OWNERSHIP: 'DISPUTED_OWNERSHIP',
  DISPUTED_REVIEW_OR_FAKE_OBSERVATION: 'DISPUTED_REVIEW_OR_FAKE_OBSERVATION',
  STALE_INFORMATION_CONFLICT: 'STALE_INFORMATION_CONFLICT',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
